version: '3'

services:
  web.api:
    container_name: web.api
    image: "reserveroom_api:latest"
    ports:
      - "8000:8000"
    networks:
      - backend

  web.front:
    build: './reserveroom_web'
    container_name: web.front
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080

  nginx:
    container_name: nginx
    image: "reserveroom_nginx:latest"
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - web.api
      - web.front

networks:
  backend:
    driver: bridge