version: '3'

services:
  reserveroom_api:
    container_name: web.api
    image: "reserveroom_api:latest"
    ports:
      - "8000:8000"
    networks:
      - backend
  nginx:
    container_name: nginx
    image: "reserveroom_nginx:latest"
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - reserveroom_api
      - reserveroom_web
  reserveroom_web:
    build: './reserveroom_web'
    container_name: web.front
    ports:
      - "8080:8080"
    environment:
      - POR=9000

networks:
  backend:
    driver: bridge