version: '3'

services:
  web.api:
    container_name: web.api
    image: "reserveroom_api:latest"
    ports:
      - "8000:8000"

  web.front:
    build: './reserveroom_web'
    container_name: web.front
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080

  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/room/ReserveRoom/reserveroom_web/public:/srv/www/static
      - /home/ubuntu/room/ReserveRoom/nginx:/etc/nginx/conf.d
    depends_on:
      - web.api
      - web.front
