version: '3'

services:
  reserveroom_api:
    container_name: web.api
    image: "reserveroom_api:latest"
    ports:
      - "8000:8000"
    networks:
      - backend
  nginx:
    container_name: nginx
    image: "reserveroom_nginx:latest"
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge